INSERT INTO CAMBIO (FROM_CURRENCY, TO_CURRENCY, CONVERSION_FACTORY) VALUES ('USD', 'BRL', 5.73);
INSERT INTO CAMBIO (FROM_CURRENCY, TO_CURRENCY, CONVERSION_FACTORY) VALUES ('USD', 'EUR', 0.84);
INSERT INTO CAMBIO (FROM_CURRENCY, TO_CURRENCY, CONVERSION_FACTORY) VALUES ('USD', 'GBP', 0.73);
INSERT INTO CAMBIO (FROM_CURRENCY, TO_CURRENCY, CONVERSION_FACTORY) VALUES ('USD', 'ARS', 92.56);
INSERT INTO CAMBIO (FROM_CURRENCY, TO_CURRENCY, CONVERSION_FACTORY) VALUES ('USD', 'CLP', 713.30);
INSERT INTO CAMBIO (FROM_CURRENCY, TO_CURRENCY, CONVERSION_FACTORY) VALUES ('USD', 'COP', 3665.00);
INSERT INTO CAMBIO (FROM_CURRENCY, TO_CURRENCY, CONVERSION_FACTORY) VALUES ('USD', 'MXN', 20.15);